[package]
edition = "2021"
name = "date-stuff"
version = "0.1.0"

[dependencies]
clap = { version = "4.5.53", features = ["derive", "color"] }
color-eyre = "0.6.5"
colored = "3.0.0"
time = { version = "0.3.44", features = ["local-offset"] }
